version: '3.3'
services:
  cricket_live_score:
    container_name: cricket-live-score-container
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php -S 0.0.0.0:80'
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    ports:
      - 91:80